### ISSUE TITLE
Adding SV vcf args

### ISSUE THREAD

**Issue by jluebeck** [edwin5588/paa_custom#8]
@edwin5588  - there is a new build of AmpliconSuite-pipeline (v1.0.0) out. It adds two new arguments
--sv_vcf  (optional, file)
--sv_vcf_no_filter  (optional, flag - only matters if --sv_vcf is set). 

It would be good to expose these in the GenePattern interface. The v1.0.0 release is also accompanied by bumps to AA and AC, but these are handled simply by rebuilding the docker image so that it pulls the latest versions from GitHub.

**Comment by edwin5588** [comment]
Will update today.

**Comment by edwin5588** [comment]
Update live on genepattern ucsd
